<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12919" started-at="2021-03-12T13:02:53Z" finished-at="2021-03-12T13:03:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12919" started-at="2021-03-12T13:02:53Z" finished-at="2021-03-12T13:03:06Z">
      <class name="AdvanceSelenium.Signup_Script">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:AdvanceSelenium.Signup_Script@34ce8af7]" name="startBrowser" is-config="true" duration-ms="6919" started-at="2021-03-12T18:32:53Z" finished-at="2021-03-12T18:33:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="open_login_page()[pri:1, instance:AdvanceSelenium.Signup_Script@34ce8af7]" name="open_login_page" duration-ms="4643" started-at="2021-03-12T18:33:00Z" description="Open Registration Page" finished-at="2021-03-12T18:33:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_login_page -->
        <test-method status="FAIL" signature="invalid_email()[pri:3, instance:AdvanceSelenium.Signup_Script@34ce8af7]" name="invalid_email" duration-ms="1260" started-at="2021-03-12T18:33:05Z" description="Invalid email_ID" finished-at="2021-03-12T18:33:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:482)
	at AdvanceSelenium.Signup_Script.invalid_email(Signup_Script.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalid_email -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:AdvanceSelenium.Signup_Script@34ce8af7]" name="closeBrowser" is-config="true" duration-ms="85" started-at="2021-03-12T18:33:06Z" finished-at="2021-03-12T18:33:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- AdvanceSelenium.Signup_Script -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
